-- Insert categories
INSERT INTO "public"."categories" (id, name, slug, description, created_at)
VALUES 
  ('tech-talks', 'Tech Talks', 'tech-talks', 'Technology and innovation events', CURRENT_TIMESTAMP),
  ('business', 'Business', 'business', 'Business and entrepreneurship events', CURRENT_TIMESTAMP),
  ('design', 'Design', 'design', 'Design and creative events', CURRENT_TIMESTAMP),
  ('health-wellness', 'Health & Wellness', 'health-wellness', 'Health and wellness events', CURRENT_TIMESTAMP),
  ('education', 'Education', 'education', 'Educational events and workshops', CURRENT_TIMESTAMP)
ON CONFLICT (id) DO UPDATE 
SET name = EXCLUDED.name,
    slug = EXCLUDED.slug,
    description = EXCLUDED.description;

-- Insert sample events
INSERT INTO "public"."events" (
  id, name, slug, description, location, venue, date, 
  start_time, end_time, image_url, is_featured, is_free, 
  price, max_attendees, attendee_count, category_id, 
  created_at, updated_at
)
VALUES 
  (
    'evt_001', 
    'Next.js Developer Conference', 
    'nextjs-developer-conference',
    'Join us for an exciting conference about Next.js and the future of web development',
    'San Francisco',
    'Moscone Center',
    '2024-04-15 00:00:00',
    '09:00 AM',
    '05:00 PM',
    'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&auto=format&fit=crop',
    true,
    false,
    299.99,
    500,
    0,
    'tech-talks',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'evt_002',
    'Startup Networking Mixer',
    'startup-networking-mixer',
    'Network with fellow entrepreneurs and investors in a casual setting',
    'New York',
    'WeWork Times Square',
    '2024-03-28 00:00:00',
    '06:00 PM',
    '09:00 PM',
    'https://images.unsplash.com/photo-1591115765373-5207764f72e4?w=800&auto=format&fit=crop',
    true,
    true,
    0,
    100,
    0,
    'business',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'evt_003',
    'UI/UX Design Workshop',
    'ui-ux-design-workshop',
    'Learn the fundamentals of UI/UX design in this hands-on workshop',
    'London',
    'Design Hub',
    '2024-04-01 00:00:00',
    '10:00 AM',
    '04:00 PM',
    'https://images.unsplash.com/photo-1552664730-d307ca884978?w=800&auto=format&fit=crop',
    false,
    false,
    149.99,
    30,
    0,
    'design',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'evt_004',
    'Wellness & Mindfulness Retreat',
    'wellness-mindfulness-retreat',
    'A day of wellness activities and mindfulness practices',
    'Los Angeles',
    'Zen Garden Center',
    '2024-04-10 00:00:00',
    '08:00 AM',
    '06:00 PM',
    'https://images.unsplash.com/photo-1599901860904-17e6ed7083a0?w=800&auto=format&fit=crop',
    true,
    false,
    199.99,
    50,
    0,
    'health-wellness',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'evt_005',
    'Python for Beginners Workshop',
    'python-for-beginners',
    'Get started with Python programming in this beginner-friendly workshop',
    'Online',
    'Zoom',
    '2024-03-25 00:00:00',
    '02:00 PM',
    '05:00 PM',
    'https://images.unsplash.com/photo-1587620962725-abab7fe55159?w=800&auto=format&fit=crop',
    false,
    false,
    79.99,
    200,
    0,
    'education',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  )
ON CONFLICT (id) DO UPDATE 
SET name = EXCLUDED.name,
    slug = EXCLUDED.slug,
    description = EXCLUDED.description,
    location = EXCLUDED.location,
    venue = EXCLUDED.venue,
    date = EXCLUDED.date,
    start_time = EXCLUDED.start_time,
    end_time = EXCLUDED.end_time,
    image_url = EXCLUDED.image_url,
    is_featured = EXCLUDED.is_featured,
    is_free = EXCLUDED.is_free,
    price = EXCLUDED.price,
    max_attendees = EXCLUDED.max_attendees,
    category_id = EXCLUDED.category_id,
    updated_at = CURRENT_TIMESTAMP; 