-- Reset sequences
TRUNCATE TABLE "public"."events" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "public"."categories" RESTART IDENTITY CASCADE;

-- Insert categories
INSERT INTO "public"."categories" (id, name, slug, description, created_at)
VALUES 
  ('tech-talks', 'Tech Talks', 'tech-talks', 'Technology and innovation events', CURRENT_TIMESTAMP),
  ('business', 'Business', 'business', 'Business and entrepreneurship events', CURRENT_TIMESTAMP),
  ('design', 'Design', 'design', 'Design and creative events', CURRENT_TIMESTAMP),
  ('health-wellness', 'Health & Wellness', 'health-wellness', 'Health and wellness events', CURRENT_TIMESTAMP),
  ('education', 'Education', 'education', 'Educational events and workshops', CURRENT_TIMESTAMP)
ON CONFLICT (id) DO UPDATE 
SET name = EXCLUDED.name,
    slug = EXCLUDED.slug,
    description = EXCLUDED.description;

-- Insert Tech Talk Events
INSERT INTO "public"."events" (
  id, name, slug, description, location, venue, date, 
  start_time, end_time, image_url, is_featured, is_free, 
  price, max_attendees, attendee_count, category_id, tags,
  created_at, updated_at
)
VALUES 
  -- Tech Talk Events
  (
    'evt_tech_001', 
    'Next.js Developer Conference', 
    'nextjs-developer-conference',
    'Join us for an exciting conference about Next.js and the future of web development. Learn from industry experts, participate in workshops, and network with fellow developers.',
    'San Francisco, CA',
    'Moscone Center',
    '2024-04-15',
    '09:00',
    '17:00',
    'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&auto=format&fit=crop',
    true,
    false,
    299.99,
    500,
    0,
    'tech-talks',
    ARRAY['nextjs', 'react', 'javascript', 'web-development', 'frontend'],
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'evt_tech_002',
    'AI in Healthcare Symposium',
    'ai-in-healthcare-symposium',
    'Explore the intersection of artificial intelligence and healthcare. Leading experts discuss the future of medical technology.',
    'Boston, MA',
    'Medical Research Center',
    '2024-05-20',
    '09:00',
    '18:00',
    'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=800&auto=format&fit=crop',
    true,
    false,
    249.99,
    300,
    0,
    'tech-talks',
    ARRAY['ai', 'healthcare', 'technology', 'medical-tech', 'innovation'],
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'evt_tech_003',
    'Blockchain & Web3 Summit',
    'blockchain-web3-summit',
    'Deep dive into blockchain technology, cryptocurrencies, and Web3 development. Network with industry pioneers and learn about the latest trends.',
    'Miami, FL',
    'Tech Hub Miami',
    '2024-06-10',
    '10:00',
    '18:00',
    'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=800&auto=format&fit=crop',
    false,
    false,
    399.99,
    400,
    0,
    'tech-talks',
    ARRAY['blockchain', 'web3', 'crypto', 'ethereum', 'technology'],
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'evt_tech_004',
    'Cloud Computing Conference',
    'cloud-computing-conference',
    'Learn about the latest in cloud computing, from serverless architecture to containerization. Featuring speakers from major cloud providers.',
    'Seattle, WA',
    'Convention Center',
    '2024-07-15',
    '09:00',
    '17:00',
    'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&auto=format&fit=crop',
    true,
    false,
    199.99,
    600,
    0,
    'tech-talks',
    ARRAY['cloud', 'aws', 'azure', 'devops', 'infrastructure'],
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'evt_tech_005',
    'Cybersecurity Workshop',
    'cybersecurity-workshop',
    'Hands-on workshop covering essential cybersecurity practices, threat detection, and prevention strategies.',
    'Washington, DC',
    'Security Institute',
    '2024-08-05',
    '10:00',
    '16:00',
    'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=800&auto=format&fit=crop',
    false,
    false,
    149.99,
    50,
    0,
    'tech-talks',
    ARRAY['security', 'cybersecurity', 'hacking', 'privacy', 'technology'],
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),

  -- Business Events
  (
    'evt_biz_001',
    'Startup Networking Mixer',
    'startup-networking-mixer',
    'Network with fellow entrepreneurs and investors in a casual setting. Perfect opportunity to pitch your ideas and find potential collaborators.',
    'New York, NY',
    'WeWork Times Square',
    '2024-03-28',
    '18:00',
    '21:00',
    'https://images.unsplash.com/photo-1591115765373-5207764f72e4?w=800&auto=format&fit=crop',
    true,
    true,
    0,
    100,
    0,
    'business',
    ARRAY['startup', 'networking', 'entrepreneurship', 'business', 'investment'],
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'evt_biz_002',
    'Sustainable Business Forum',
    'sustainable-business-forum',
    'Join industry leaders in discussing sustainable business practices and environmental responsibility in the corporate world.',
    'Seattle, WA',
    'Green Business Center',
    '2024-06-15',
    '10:00',
    '16:00',
    'https://images.unsplash.com/photo-1536784058511-2fac13abf62e?w=800&auto=format&fit=crop',
    false,
    false,
    179.99,
    150,
    0,
    'business',
    ARRAY['sustainability', 'business', 'environment', 'green-tech', 'corporate'],
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'evt_biz_003',
    'Digital Marketing Masterclass',
    'digital-marketing-masterclass',
    'Comprehensive workshop on digital marketing strategies, SEO, social media, and content marketing.',
    'Chicago, IL',
    'Marketing Hub',
    '2024-05-10',
    '09:00',
    '17:00',
    'https://images.unsplash.com/photo-1557838923-2985c318be48?w=800&auto=format&fit=crop',
    true,
    false,
    249.99,
    75,
    0,
    'business',
    ARRAY['marketing', 'digital', 'seo', 'social-media', 'content'],
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'evt_biz_004',
    'Financial Planning Summit',
    'financial-planning-summit',
    'Expert insights on personal and business financial planning, investment strategies, and wealth management.',
    'Houston, TX',
    'Finance Center',
    '2024-07-20',
    '10:00',
    '18:00',
    'https://images.unsplash.com/photo-1579532537598-459ecdaf39cc?w=800&auto=format&fit=crop',
    false,
    false,
    299.99,
    200,
    0,
    'business',
    ARRAY['finance', 'investment', 'planning', 'wealth', 'business'],
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'evt_biz_005',
    'Women in Leadership Conference',
    'women-in-leadership',
    'Celebrating and empowering women leaders in business. Featuring keynotes, panels, and networking opportunities.',
    'Los Angeles, CA',
    'Leadership Center',
    '2024-09-15',
    '09:00',
    '17:00',
    'https://images.unsplash.com/photo-1573164713988-8665fc963095?w=800&auto=format&fit=crop',
    true,
    false,
    199.99,
    300,
    0,
    'business',
    ARRAY['leadership', 'women', 'business', 'empowerment', 'networking'],
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),

  -- Design Events
  (
    'evt_design_001',
    'UI/UX Design Workshop',
    'ui-ux-design-workshop',
    'Learn the fundamentals of UI/UX design in this hands-on workshop. From user research to prototyping, cover all aspects of the design process.',
    'London, UK',
    'Design Hub',
    '2024-04-01',
    '10:00',
    '16:00',
    'https://images.unsplash.com/photo-1552664730-d307ca884978?w=800&auto=format&fit=crop',
    false,
    false,
    149.99,
    30,
    0,
    'design',
    ARRAY['design', 'ui-ux', 'workshop', 'creative', 'figma'],
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'evt_design_002',
    'Product Design Conference',
    'product-design-conference',
    'Annual conference bringing together product designers to share insights, trends, and best practices.',
    'San Francisco, CA',
    'Design Center',
    '2024-05-25',
    '09:00',
    '18:00',
    'https://images.unsplash.com/photo-1587440871875-191322ee64b0?w=800&auto=format&fit=crop',
    true,
    false,
    299.99,
    400,
    0,
    'design',
    ARRAY['product-design', 'innovation', 'design-thinking', 'ux', 'conference'],
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'evt_design_003',
    'Brand Identity Workshop',
    'brand-identity-workshop',
    'Create compelling brand identities through logo design, typography, and visual storytelling.',
    'New York, NY',
    'Creative Studio',
    '2024-06-20',
    '10:00',
    '16:00',
    'https://images.unsplash.com/photo-1572044162444-ad60f128bdea?w=800&auto=format&fit=crop',
    false,
    false,
    179.99,
    25,
    0,
    'design',
    ARRAY['branding', 'logo-design', 'typography', 'design', 'creative'],
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'evt_design_004',
    'Motion Design Festival',
    'motion-design-festival',
    'Celebrate the art of motion design with workshops, screenings, and talks from industry leaders.',
    'Los Angeles, CA',
    'Animation Studio',
    '2024-07-10',
    '09:00',
    '20:00',
    'https://images.unsplash.com/photo-1550784343-6bd0ce5d600b?w=800&auto=format&fit=crop',
    true,
    false,
    249.99,
    300,
    0,
    'design',
    ARRAY['motion-design', 'animation', 'after-effects', 'creative', 'festival'],
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'evt_design_005',
    'Web Design Masterclass',
    'web-design-masterclass',
    'Master modern web design principles, responsive layouts, and the latest design tools.',
    'Toronto, CA',
    'Tech Campus',
    '2024-08-15',
    '10:00',
    '17:00',
    'https://images.unsplash.com/photo-1581291518857-4e27b48ff24e?w=800&auto=format&fit=crop',
    false,
    false,
    199.99,
    50,
    0,
    'design',
    ARRAY['web-design', 'responsive', 'css', 'design', 'development'],
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),

  -- Health & Wellness Events
  (
    'evt_health_001',
    'Wellness & Mindfulness Retreat',
    'wellness-mindfulness-retreat',
    'A day of wellness activities and mindfulness practices. Includes yoga sessions, meditation workshops, and healthy living discussions.',
    'Los Angeles, CA',
    'Zen Garden Center',
    '2024-04-10',
    '08:00',
    '18:00',
    'https://images.unsplash.com/photo-1599901860904-17e6ed7083a0?w=800&auto=format&fit=crop',
    true,
    false,
    199.99,
    50,
    0,
    'health-wellness',
    ARRAY['wellness', 'mindfulness', 'yoga', 'meditation', 'health'],
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'evt_health_002',
    'Nutrition and Cooking Workshop',
    'nutrition-cooking-workshop',
    'Learn about healthy eating and cook nutritious meals with expert chefs and nutritionists.',
    'Portland, OR',
    'Culinary Institute',
    '2024-05-15',
    '10:00',
    '16:00',
    'https://images.unsplash.com/photo-1466637574441-749b8f19452f?w=800&auto=format&fit=crop',
    false,
    false,
    149.99,
    30,
    0,
    'health-wellness',
    ARRAY['nutrition', 'cooking', 'health', 'food', 'wellness'],
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'evt_health_003',
    'Mental Health Symposium',
    'mental-health-symposium',
    'Expert discussions on mental health, stress management, and emotional well-being.',
    'Chicago, IL',
    'Wellness Center',
    '2024-06-25',
    '09:00',
    '17:00',
    'https://images.unsplash.com/photo-1493836512294-502baa1986e2?w=800&auto=format&fit=crop',
    true,
    false,
    179.99,
    200,
    0,
    'health-wellness',
    ARRAY['mental-health', 'wellness', 'psychology', 'health', 'self-care'],
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'evt_health_004',
    'Fitness Training Summit',
    'fitness-training-summit',
    'Connect with fitness experts, learn new training techniques, and explore the latest in exercise science.',
    'Miami, FL',
    'Sports Complex',
    '2024-07-20',
    '08:00',
    '16:00',
    'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=800&auto=format&fit=crop',
    false,
    false,
    249.99,
    150,
    0,
    'health-wellness',
    ARRAY['fitness', 'training', 'exercise', 'health', 'wellness'],
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'evt_health_005',
    'Holistic Health Fair',
    'holistic-health-fair',
    'Explore alternative medicine, natural healing practices, and holistic wellness approaches.',
    'Denver, CO',
    'Natural Health Center',
    '2024-08-10',
    '10:00',
    '18:00',
    'https://images.unsplash.com/photo-1498837167922-ddd27525d352?w=800&auto=format&fit=crop',
    true,
    false,
    129.99,
    300,
    0,
    'health-wellness',
    ARRAY['holistic', 'natural-health', 'alternative-medicine', 'wellness', 'healing'],
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),

  -- Education Events
  (
    'evt_edu_001',
    'Python for Data Science',
    'python-for-data-science',
    'Get started with Python programming for data science. Learn data analysis, visualization, and machine learning basics.',
    'Online',
    'Zoom',
    '2024-03-25',
    '14:00',
    '17:00',
    'https://images.unsplash.com/photo-1587620962725-abab7fe55159?w=800&auto=format&fit=crop',
    false,
    false,
    79.99,
    200,
    0,
    'education',
    ARRAY['python', 'data-science', 'programming', 'machine-learning', 'education'],
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'evt_edu_002',
    'Language Learning Workshop',
    'language-learning-workshop',
    'Intensive language learning workshop covering effective study techniques and cultural insights.',
    'Boston, MA',
    'Language Institute',
    '2024-05-05',
    '09:00',
    '16:00',
    'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800&auto=format&fit=crop',
    false,
    false,
    149.99,
    50,
    0,
    'education',
    ARRAY['language', 'learning', 'education', 'culture', 'workshop'],
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'evt_edu_003',
    'Creative Writing Masterclass',
    'creative-writing-masterclass',
    'Develop your writing skills with guidance from published authors and writing professionals.',
    'Austin, TX',
    'Writers Studio',
    '2024-06-15',
    '10:00',
    '17:00',
    'https://images.unsplash.com/photo-1455390582262-044cdead277a?w=800&auto=format&fit=crop',
    true,
    false,
    199.99,
    40,
    0,
    'education',
    ARRAY['writing', 'creative', 'literature', 'education', 'workshop'],
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'evt_edu_004',
    'STEM Education Conference',
    'stem-education-conference',
    'Conference focusing on innovative approaches to teaching Science, Technology, Engineering, and Mathematics.',
    'Washington, DC',
    'Education Center',
    '2024-07-25',
    '09:00',
    '18:00',
    'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800&auto=format&fit=crop',
    true,
    false,
    279.99,
    300,
    0,
    'education',
    ARRAY['stem', 'education', 'science', 'technology', 'mathematics'],
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'evt_edu_005',
    'Digital Skills Bootcamp',
    'digital-skills-bootcamp',
    'Intensive training in essential digital skills for the modern workplace.',
    'Seattle, WA',
    'Tech Academy',
    '2024-08-20',
    '09:00',
    '17:00',
    'https://images.unsplash.com/photo-1531482615713-2afd69097998?w=800&auto=format&fit=crop',
    false,
    false,
    299.99,
    100,
    0,
    'education',
    ARRAY['digital-skills', 'technology', 'education', 'career', 'training'],
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  )
ON CONFLICT (id) DO UPDATE 
SET name = EXCLUDED.name,
    slug = EXCLUDED.slug,
    description = EXCLUDED.description,
    tags = EXCLUDED.tags,
    image_url = EXCLUDED.image_url,
    date = EXCLUDED.date,
    price = EXCLUDED.price,
    is_featured = EXCLUDED.is_featured; 