-- Insert categories
INSERT INTO public.categories (id, created_at, name, slug, description) VALUES
  ('cat_01', NOW(), 'Tech Talks', 'tech-talks', 'Technology conferences, workshops, and meetups'),
  ('cat_02', NOW(), 'Business', 'business', 'Networking events, seminars, and conferences'),
  ('cat_03', NOW(), 'Design', 'design', 'Design workshops, UX/UI meetups, and creative sessions'),
  ('cat_04', NOW(), 'Health & Wellness', 'health-wellness', 'Virtual fitness classes, meditation sessions, and health seminars'),
  ('cat_05', NOW(), 'Education', 'education', 'Online courses, workshops, and educational seminars');

-- Insert some sample events
INSERT INTO public.events (
  id, created_at, updated_at, name, slug, description, venue, 
  date, start_time, end_time, is_featured, is_free, price, 
  max_attendees, attendee_count, category_id, image_url
) VALUES
  (
    'evt_01',
    NOW(),
    NOW(),
    'Web Development Workshop 2024',
    'web-development-workshop-2024',
    'Learn the latest web development technologies and best practices',
    'Virtual Event',
    NOW() + INTERVAL '7 days',
    '09:00',
    '17:00',
    true,
    false,
    49.99,
    100,
    0,
    'cat_01',
    'https://images.unsplash.com/photo-1517694712202-14dd9538aa97'
  ),
  (
    'evt_02',
    NOW(),
    NOW(),
    'Startup Networking Mixer',
    'startup-networking-mixer',
    'Connect with fellow entrepreneurs and investors',
    'Virtual Event',
    NOW() + INTERVAL '14 days',
    '18:00',
    '21:00',
    true,
    true,
    0,
    50,
    0,
    'cat_02',
    'https://images.unsplash.com/photo-1515187029135-18ee286d815b'
  ),
  (
    'evt_03',
    NOW(),
    NOW(),
    'UI/UX Design Principles',
    'ui-ux-design-principles',
    'Master the fundamentals of user interface and experience design',
    'Virtual Event',
    NOW() + INTERVAL '10 days',
    '10:00',
    '16:00',
    true,
    false,
    79.99,
    75,
    0,
    'cat_03',
    'https://images.unsplash.com/photo-1586717791821-3f44a563fa4c'
  ),
  (
    'evt_04',
    NOW(),
    NOW(),
    'Mindfulness Meditation Session',
    'mindfulness-meditation-session',
    'Learn meditation techniques for stress relief and mental clarity',
    'Virtual Event',
    NOW() + INTERVAL '5 days',
    '08:00',
    '09:00',
    false,
    true,
    0,
    200,
    0,
    'cat_04',
    'https://images.unsplash.com/photo-1593811167562-9cef47bfc4a7'
  ),
  (
    'evt_05',
    NOW(),
    NOW(),
    'Digital Marketing Masterclass',
    'digital-marketing-masterclass',
    'Comprehensive overview of modern digital marketing strategies',
    'Virtual Event',
    NOW() + INTERVAL '21 days',
    '13:00',
    '18:00',
    false,
    false,
    129.99,
    150,
    0,
    'cat_02',
    'https://images.unsplash.com/photo-1557838923-2985c318be48'
  ); 